### ISSUE TITLE
Il y a pas de livereload sur les templates .twig ?

### ISSUE THREAD

**Issue by mmaayylliiss** [wearemd/wordpress-starter#2]

**Comment by Awea** [comment]
Il y a du livereload sur les templates twig (voir [dev.js](https://github.com/wearemd/wordpress-starter/blob/master/gulp/env/dev.js#L17)).

**Comment by mmaayylliiss** [comment]
Deprecated because I’m a jerk (I was on localhost:3010 -_-)
