### ISSUE TITLE
Fix 404 template display

### ISSUE THREAD

**Issue by mmaayylliiss** [wearemd/wordpress-starter#5]
404 tpl is not used for 404 page

**Comment by Awea** [comment]
@mmaayylliiss There is no fix for that. You just need to activate WordPress pretty permalinks :)

**Comment by Awea** [comment]
I'll add it in the `make setup` process (see [wp rewrite](https://developer.wordpress.org/cli/commands/rewrite/structure/)).

**Comment by mmaayylliiss** [comment]
Ok ✅
