### ISSUE TITLE
When fr_FR is set as site language, fr_FR translations must be used in front

### ISSUE THREAD

**Issue by mmaayylliiss** [wearemd/wordpress-starter#71]
@Awea Do the test :)

**Comment by Awea** [comment]
> Do the test :)

@mmaayylliiss already done a test before pushing. Are you sure you have run: 
- `make clean`
- `make create-theme` => change only the language
- `make setup`
- `make`

**Comment by Awea** [comment]
The problem occurs after a `make create-theme` with a different `themeName`, I think the problem comes from the `.po` files header which include a different `themeName`.

**Comment by Awea** [comment]
C'est ok.

**Comment by mmaayylliiss** [comment]
✅
