### ISSUE TITLE
Rename navbar_footer > nav_footer

### ISSUE THREAD

**Issue by mmaayylliiss** [wearemd/wordpress-starter#73]
A footer nav is rarely a navbar. So we should use “nav” term because it is more generic.

**Comment by mmaayylliiss** [comment]
@Awea Ne pas oublier de renommer `navbar-footer.twig`

**Comment by Awea** [comment]
> Ne pas oublier de renommer navbar-footer.twig

@mmaayylliiss C'est déjà fais :3

**Comment by mmaayylliiss** [comment]
✅
