### ISSUE TITLE
Solve remaining md starter occurrences issue

### ISSUE THREAD

**Issue by mmaayylliiss** [wearemd/wordpress-starter#78]
When user creates a theme and customizes its name, there are some `MD Starter`/`MD_Starter`/`md_starter` occurrences that are not renamed (in **theme PHP files**).

Shouldn’t we replace them using theme name too?
```
MD Starter > Theme name
MD_Starter > Theme_Name
md_starter > theme_name
```

**Or** maybe we can name these this way (so there is no need to rename them while creating a theme):
```
MD Starter > WP Starter
MD_Starter > WP_Starter
md_starter > wp_starter
```

@Awea What solution do you prefer? I prefer the second one because it is simpler.

**Comment by Awea** [comment]
- Renommer reset.php en disable_wp_emoji.php
- Renommer sanitize-wysiwyg.php en customize_tinymce.php

**Comment by mmaayylliiss** [comment]
✅
